ALTER TABLE customer_returns
    MODIFY COLUMN status ENUM(
        'REQUESTED','NEEDS_MORE_INFO','APPROVED','RETURNING','SHIPPING_FAILED',
        'RECEIVED','INSPECTED_OK','INSPECTED_FAILED','REJECTED','DISPUTED',
        'REFUND_PENDING','CANCELLED','REFUNDED','REPLACED'
    ) NOT NULL;

ALTER TABLE customer_return_histories
    MODIFY COLUMN old_status ENUM(
        'REQUESTED','NEEDS_MORE_INFO','APPROVED','RETURNING','SHIPPING_FAILED',
        'RECEIVED','INSPECTED_OK','INSPECTED_FAILED','REJECTED','DISPUTED',
        'REFUND_PENDING','CANCELLED','REFUNDED','REPLACED'
    ) NULL,
    MODIFY COLUMN new_status ENUM(
        'REQUESTED','NEEDS_MORE_INFO','APPROVED','RETURNING','SHIPPING_FAILED',
        'RECEIVED','INSPECTED_OK','INSPECTED_FAILED','REJECTED','DISPUTED',
        'REFUND_PENDING','CANCELLED','REFUNDED','REPLACED'
    ) NOT NULL;
