package com.example.new_toy_store.accounting.domain;

public enum AccountingSourceType {
    OPENING_BALANCE,
    OWNER_CAPITAL,
    CUSTOMER_PAYMENT,
    CUSTOMER_REFUND,
    ORDER_COMPLETION,
    CUSTOMER_RETURN_STOCK,
    IMPORT_RECEIPT,
    SUPPLIER_PAYMENT,
    SUPPLIER_RETURN_SHIPMENT,
    SUPPLIER_RETURN_RESTORATION,
    OPERATING_EXPENSE,
    FUND_TRANSFER,
    MANUAL_ADJUSTMENT,
    REVERSAL
}
