spring:
  application:
    name: new_toy_store

  datasource:
    url: jdbc:mysql://localhost:3306/new_toy_store
    username: root
    password: Huynguyen_07

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: frocoding8888@gmail.com
    password: izsl leeg scsg novm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  app:
    cart:
      cleanup:
        cron: "0 0 0 * * ?"
        zone: "Asia/Ho_Chi_Minh"
    order:
      timeout:
        cron: "0 */15 * * * *"
        zone: "Asia/Ho_Chi_Minh"
        expiration-minutes: 30
    schedule:
      supplier-return:
        cron: "0 0 8 * * ?"
        alert-hours: 48
        critical-hours: 96